name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels_windows_macos:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build wheels
        env:
          CIBW_BUILD: 'cp38-* cp39-* cp310-* cp311-*'
        uses: pypa/cibuildwheel@v2.16.2

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_ubuntu1:
    name: Build wheels on ubuntu-latest cp38 cp39
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build wheels
        env:
          CIBW_BUILD: 'cp38-* cp39-*'
        uses: pypa/cibuildwheel@v2.16.2

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheels_ubuntu2:
    name: Build wheels on ubuntu-latest cp310 cp311
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build wheels
        env:
          CIBW_BUILD: 'cp310-* cp311-*'
        uses: pypa/cibuildwheel@v2.16.2

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  publish_on_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [ build_sdist, build_wheels_windows_macos, build_wheels_ubuntu1, build_wheels_ubuntu2 ]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
